// LUMINA Dummy Data - 100 Entries Total

export const integrityVaultData = [
  {"id":"IV-001","timestamp":"2025-02-01 08:12","original":"Rp 2.400.000","new":"Rp 2.410.000","risk":"Medium","hash":"0x8af21bd…","status":"Modified"},
  {"id":"IV-002","timestamp":"2025-02-01 08:33","original":"Rp 950.000","new":"Rp 950.000","risk":"Low","hash":"0x7ce8831…","status":"Clean"},
  {"id":"IV-003","timestamp":"2025-02-01 09:12","original":"Rp 5.000.000","new":"Rp 4.200.000","risk":"High","hash":"0x29ab119…","status":"Flagged"},
  {"id":"IV-004","timestamp":"2025-02-01 09:20","original":"Rp 1.200.000","new":"Rp 1.200.000","risk":"Low","hash":"0xb331e71…","status":"Clean"},
  {"id":"IV-005","timestamp":"2025-02-01 10:12","original":"Rp 11.000.000","new":"Rp 11.250.000","risk":"Medium","hash":"0x91fe22a…","status":"Modified"},
  {"id":"IV-006","timestamp":"2025-02-01 11:01","original":"Rp 760.000","new":"Rp 730.000","risk":"Medium","hash":"0x4bc11d7…","status":"Modified"},
  {"id":"IV-007","timestamp":"2025-02-01 11:59","original":"Rp 2.100.000","new":"Rp 2.100.000","risk":"Low","hash":"0xa5f71d3…","status":"Clean"},
  {"id":"IV-008","timestamp":"2025-02-01 12:14","original":"Rp 3.250.000","new":"Rp 3.250.000","risk":"Low","hash":"0x518acdf…","status":"Clean"},
  {"id":"IV-009","timestamp":"2025-02-01 12:40","original":"Rp 9.000.000","new":"Rp 7.000.000","risk":"High","hash":"0x177e8fa…","status":"Flagged"},
  {"id":"IV-010","timestamp":"2025-02-01 13:05","original":"Rp 1.000.000","new":"Rp 1.100.000","risk":"Medium","hash":"0x92cfa1d…","status":"Modified"},
  {"id":"IV-011","timestamp":"2025-02-01 14:01","original":"Rp 2.000.000","new":"Rp 2.000.000","risk":"Low","hash":"0x00ffbb0…","status":"Clean"},
  {"id":"IV-012","timestamp":"2025-02-01 15:21","original":"Rp 1.250.000","new":"Rp 1.250.000","risk":"Low","hash":"0x449e9ce…","status":"Clean"},
  {"id":"IV-013","timestamp":"2025-02-01 15:59","original":"Rp 6.300.000","new":"Rp 6.500.000","risk":"Medium","hash":"0x02e8d01…","status":"Modified"},
  {"id":"IV-014","timestamp":"2025-02-01 16:22","original":"Rp 3.600.000","new":"Rp 3.600.000","risk":"Low","hash":"0xb989ace…","status":"Clean"},
  {"id":"IV-015","timestamp":"2025-02-01 17:10","original":"Rp 900.000","new":"Rp 900.000","risk":"Low","hash":"0xcdff138…","status":"Clean"},
  {"id":"IV-016","timestamp":"2025-02-01 18:55","original":"Rp 8.000.000","new":"Rp 7.200.000","risk":"High","hash":"0x128be02…","status":"Flagged"},
  {"id":"IV-017","timestamp":"2025-02-01 19:33","original":"Rp 2.500.000","new":"Rp 2.500.000","risk":"Low","hash":"0x99fdc21…","status":"Clean"},
  {"id":"IV-018","timestamp":"2025-02-01 20:14","original":"Rp 1.750.000","new":"Rp 1.820.000","risk":"Medium","hash":"0x17ffbd3…","status":"Modified"},
  {"id":"IV-019","timestamp":"2025-02-01 20:44","original":"Rp 4.500.000","new":"Rp 4.500.000","risk":"Low","hash":"0x37e2a17…","status":"Clean"},
  {"id":"IV-020","timestamp":"2025-02-01 21:05","original":"Rp 3.200.000","new":"Rp 3.900.000","risk":"High","hash":"0xcaff179…","status":"Flagged"}
];

export const trustProfileData = [
  {"activity":"Transaksi rutin bulanan","consistency":"Tinggi","deviation":"2%","impact":"+4","status":"Stabil"},
  {"activity":"Pembelian harian kecil","consistency":"Sedang","deviation":"5%","impact":"+1","status":"Normal"},
  {"activity":"Transfer sore hari","consistency":"Tinggi","deviation":"1%","impact":"+3","status":"Stabil"},
  {"activity":"Kenaikan nominal tiba-tiba","consistency":"Rendah","deviation":"22%","impact":"-8","status":"Perlu Perhatian"},
  {"activity":"Pengulangan transaksi sama","consistency":"Tinggi","deviation":"0%","impact":"+2","status":"Stabil"},
  {"activity":"Durasi transaksi di luar jam biasa","consistency":"Sedang","deviation":"14%","impact":"-3","status":"Aneh"},
  {"activity":"Pembayaran tagihan rutin","consistency":"Tinggi","deviation":"3%","impact":"+3","status":"Stabil"},
  {"activity":"Perubahan pola tanggal","consistency":"Sedang","deviation":"9%","impact":"-1","status":"Normal"},
  {"activity":"Transaksi besar malam hari","consistency":"Rendah","deviation":"26%","impact":"-10","status":"Risiko Tinggi"},
  {"activity":"Top-up dompet digital","consistency":"Tinggi","deviation":"2%","impact":"+2","status":"Stabil"},
  {"activity":"Penarikan mendadak","consistency":"Rendah","deviation":"19%","impact":"-7","status":"Awas"},
  {"activity":"Pembelian kebutuhan pokok","consistency":"Tinggi","deviation":"1%","impact":"+1","status":"Stabil"},
  {"activity":"Pengiriman valas kecil","consistency":"Sedang","deviation":"12%","impact":"-2","status":"Normal"},
  {"activity":"Lonjakan frekuensi transaksi","consistency":"Rendah","deviation":"30%","impact":"-11","status":"Abnormal"},
  {"activity":"Pembelian di merchant tetap","consistency":"Tinggi","deviation":"3%","impact":"+2","status":"Stabil"},
  {"activity":"Polanya tiba-tiba berhenti","consistency":"Rendah","deviation":"17%","impact":"-4","status":"Perlu Review"},
  {"activity":"Nominal konsisten 3 bulan","consistency":"Tinggi","deviation":"0%","impact":"+4","status":"Stabil"},
  {"activity":"Kenaikan tren kecil","consistency":"Sedang","deviation":"6%","impact":"0","status":"Normal"},
  {"activity":"Aktivitas ganda dalam 5 menit","consistency":"Rendah","deviation":"15%","impact":"-3","status":"Awas"},
  {"activity":"Transaksi per jam aman","consistency":"Tinggi","deviation":"1%","impact":"+2","status":"Stabil"}
];

export const silentWatchData = [
  {"pattern":"Pola frekuensi tinggi mendadak","severity":"Tinggi","window":"03.00–04.00","summary":"Lonjakan 4x transaksi dalam 12 menit.","action":"Audit manual disarankan"},
  {"pattern":"Transaksi berulang nominal sama","severity":"Sedang","window":"Siang","summary":"8 transaksi Rp 150.000 tanpa alasan jelas.","action":"Review ringan"},
  {"pattern":"Penurunan nominal drastis","severity":"Tinggi","window":"Malam","summary":"Nominal turun 70% dalam 1 jam.","action":"Periksa konteks"},
  {"pattern":"Aktivitas lintas negara cepat","severity":"Sedang","window":"Pagi","summary":"Valas masuk-keluar dalam 10 menit.","action":"Analisa lebih lanjut"},
  {"pattern":"Transaksi idle lalu aktif tiba-tiba","severity":"Rendah","window":"Sore","summary":"2 hari tidak aktif, tiba-tiba 5 transaksi.","action":"Pantau"},
  {"pattern":"Perubahan jam kebiasaan","severity":"Sedang","window":"Dini hari","summary":"Transaksi jam 02.30 padahal biasanya jam 9 pagi.","action":"Cek pola lama"},
  {"pattern":"Kecocokan pola fraud ringan","severity":"Tinggi","window":"Malam","summary":"Mirip pola fraud kartu kredit.","action":"Audit segera"},
  {"pattern":"Pergerakan nominal fluktuatif","severity":"Sedang","window":"Sore","summary":"Naik-turun lebih dari 20% dalam sejam.","action":"Pantau tambahan"},
  {"pattern":"Duplikasi transaksi","severity":"Tinggi","window":"Siang","summary":"3 duplikasi ditemukan.","action":"Investigasi"},
  {"pattern":"Pola merchant tidak biasa","severity":"Rendah","window":"Pagi","summary":"Belanja di kategori yang tidak pernah muncul.","action":"Review ringan"},
  {"pattern":"Lonjakan tren mingguan","severity":"Sedang","window":"Minggu","summary":"Kenaikan 35% dari kebiasaan.","action":"Analisa konteks"},
  {"pattern":"Transaksi spam kecil","severity":"Sedang","window":"Siang","summary":"10 transaksi < Rp 10.000.","action":"Pantau"},
  {"pattern":"Akses dari zona waktu berbeda","severity":"Tinggi","window":"Subuh","summary":"Akses tercatat dari zona luar kebiasaan.","action":"Audit keamanan"},
  {"pattern":"Penurunan frekuensi ekstrem","severity":"Sedang","window":"Pagi","summary":"Frek turun 90% tiba-tiba.","action":"Pantau"},
  {"pattern":"Blok waktu padat aneh","severity":"Sedang","window":"09.00–09.15","summary":"9 transaksi dalam 15 menit.","action":"Review cepat"},
  {"pattern":"Potensi bot-like pattern","severity":"Tinggi","window":"Malem","summary":"Interval transaksi sangat simetris.","action":"Audit AI"},
  {"pattern":"Lonjakan merchant internasional","severity":"Sedang","window":"Sore","summary":"Belanja di merchant luar negeri.","action":"Validasi manual"},
  {"pattern":"Risiko sedang dari cluster pola","severity":"Sedang","window":"Acak","summary":"Cluster menunjukkan deviasi 12%.","action":"Pantau"},
  {"pattern":"Pengulangan kategori sama","severity":"Rendah","window":"Hari kerja","summary":"Kategori sama selama 5 hari.","action":"Normal, tetap pantau"},
  {"pattern":"Lonjakan transaksi non-rutin","severity":"Tinggi","window":"Acak","summary":"Pola tidak sesuai histori 3 bulan.","action":"Investigasi penuh"}
];

export const insightBoardData = [
  {"code":"TX-101","status":"Bersih","evidence":2,"reason":"Nominal sesuai pola","action":"Tidak ada"},
  {"code":"TX-102","status":"Perlu Review","evidence":4,"reason":"Jam transaksi tidak biasa","action":"Analisa konteks"},
  {"code":"TX-103","status":"Terindikasi","evidence":7,"reason":"Mirip pola fraud OJK 2024","action":"Audit manual"},
  {"code":"TX-104","status":"Bersih","evidence":1,"reason":"Pola minggu stabil","action":"Tidak ada"},
  {"code":"TX-105","status":"Perlu Review","evidence":3,"reason":"Duplikasi ringan","action":"Konfirmasi"},
  {"code":"TX-106","status":"Bersih","evidence":1,"reason":"Tidak ada tanda anomali","action":"Tidak ada"},
  {"code":"TX-107","status":"Terindikasi","evidence":6,"reason":"Deviasi > 25%","action":"Investigasi"},
  {"code":"TX-108","status":"Perlu Review","evidence":2,"reason":"Merchant baru","action":"Cek ulang"},
  {"code":"TX-109","status":"Bersih","evidence":2,"reason":"Nominal kecil aman","action":"Tidak ada"},
  {"code":"TX-110","status":"Bersih","evidence":1,"reason":"Stabil 3 bulan","action":"Tidak ada"},
  {"code":"TX-111","status":"Terindikasi","evidence":8,"reason":"Anomali jam + frekuensi","action":"Audit manual"},
  {"code":"TX-112","status":"Perlu Review","evidence":3,"reason":"Risiko sedang","action":"Analisa"},
  {"code":"TX-113","status":"Bersih","evidence":1,"reason":"Tidak ada pola janggal","action":"Tidak ada"},
  {"code":"TX-114","status":"Terindikasi","evidence":9,"reason":"Pola lintas negara cepat","action":"Investigasi"},
  {"code":"TX-115","status":"Perlu Review","evidence":3,"reason":"Kenaikan kecil","action":"Pantau"},
  {"code":"TX-116","status":"Bersih","evidence":1,"reason":"Transaksi normal","action":"Tidak ada"},
  {"code":"TX-117","status":"Perlu Review","evidence":4,"reason":"Anomali ringan","action":"Review manual"},
  {"code":"TX-118","status":"Terindikasi","evidence":10,"reason":"Risiko tinggi silang","action":"Audit"},
  {"code":"TX-119","status":"Bersih","evidence":2,"reason":"Valid oleh Vault","action":"Tidak ada"},
  {"code":"TX-120","status":"Perlu Review","evidence":3,"reason":"Konteks tidak jelas","action":"Cek manual"}
];

export const secureExchangeData = [
  {"pair":"IDR → USD","amount":"3.000.000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"USD → JPY","amount":"150","risk":"Sedang","result":"Perlu Review","vault":"Verifikasi"},
  {"pair":"IDR → EUR","amount":"8.000.000","risk":"Tinggi","result":"Ditolak","vault":"Flagged"},
  {"pair":"EUR → IDR","amount":"200","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"IDR → SGD","amount":"1.200.000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"IDR → GBP","amount":"12.000.000","risk":"Tinggi","result":"Ditolak","vault":"Bahaya"},
  {"pair":"JPY → IDR","amount":"50000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"USD → IDR","amount":"300","risk":"Sedang","result":"Review","vault":"Stabil"},
  {"pair":"IDR → THB","amount":"2.000.000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"AUD → IDR","amount":"100","risk":"Sedang","result":"Review","vault":"Validasi"},
  {"pair":"KRW → IDR","amount":"650000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"IDR → AUD","amount":"4.400.000","risk":"Sedang","result":"Review","vault":"Cek"},
  {"pair":"IDR → MYR","amount":"1.600.000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"IDR → SAR","amount":"7.200.000","risk":"Sedang","result":"Review","vault":"Periksa"},
  {"pair":"EUR → SGD","amount":"120","risk":"Sedang","result":"Review","vault":"Validasi"},
  {"pair":"IDR → CNY","amount":"5.000.000","risk":"Sedang","result":"Review","vault":"Pantau"},
  {"pair":"CNY → IDR","amount":"1500","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"SGD → IDR","amount":"180","risk":"Sedang","result":"Perlu Review","vault":"Cek"},
  {"pair":"IDR → KRW","amount":"3.500.000","risk":"Rendah","result":"Disetujui","vault":"Aman"},
  {"pair":"IDR → USD","amount":"15.000.000","risk":"Tinggi","result":"Ditolak","vault":"Flagged"}
];
